/** @file client2.cpp
 * @brief Client specific logic
 * client authentication logic, Client main loop
 */

#include "auth.hpp"
#include "chat2.hpp"
#include <arpa/inet.h>
#include <cctype>
#include <cerrno>
#include <csignal>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <ctime>
#include <fcntl.h>
#include <map>
#include <netinet/in.h>
#include <openssl/err.h>
#include <openssl/ssl.h>
#include <string>
#include <sys/event.h>
#include <sys/socket.h>
#include <unistd.h>
#include <vector>

#define CLIENT_TIMER_IDENT 999
static time_t g_last_server_activity = time(nullptr);

/**
 * @class ClientSession
 * @brief All the data related to the client, socket, name, input and output
 * buffer
 */
struct ClientSession {
  /**
   * @brief Client Socket
   */
  int fd;

  SSL *ssl = nullptr;

  time_t last_seen = time(nullptr);

  int num_reconnects = 0;

  /**
   * @brief Username of the client
   */
  std::string username;

  /**
   * @brief Special client specific token generated by the server, used by the
   * client incase of reconnection
   */
  std::string token;

  /**
   * @brief input buffer, data received from the server is placed here
   */
  std::vector<uint8_t> rx_buffer;
  /**
   * @brief output buffer, data transmitted by the client to the server is
   * placed here
   */
  std::vector<uint8_t> tx_buffer;

  /**
   * @brief Default constructor, does nothing.
   */
  ClientSession() {}

  /**
   * @brief Primary constructor of ClientSession, initializes client socket and
   * reserves both the buffer with size 64KB.
   *
   * @param fd Client Socket (file descriptor)
   */
  ClientSession(int fd, SSL *ssl) : fd(fd), ssl(ssl) {
    rx_buffer.reserve(65536);
    tx_buffer.reserve(65536);
  }
};

/**
 * @brief Dictionary with key being the client socket and value being the
 * session corresponding to that socket
 */
std::map<int, ClientSession> g_clients;

/**
 * @class sockaddr_in
 * @brief IP address struct
 *
 */
struct sockaddr_in serverAddress{};

/**
 * @brief Sets a socket to non blocking
 * @param fd File descriptor of the socket to set non blocking
 * @return true if descriptor was successfully set to non blocking, false if
 * system call failed
 */
bool set_nonblocking(int fd) {
  int flags = fcntl(fd, F_GETFL, 0);
  if (flags == -1)
    return false;
  return fcntl(fd, F_SETFL, flags | O_NONBLOCK) != -1;
}

/**
 * @brief Handles the authentication logic for the client
 * Handles both registration and login, a packet containing name|password is
 * sent to the server for authentication.
 * @return success: client fd | faliure: -1
 */
int client_login(SSL_CTX *ssl_ctx) {
  setupNcurses();
  nodelay(inputWin, true);

  std::string ip;
  printw("Enter server IP (Press enter for localhost 127.0.0.1): ");
  ip = read_input_line(15);

  if (ip.empty())
    ip = "127.0.0.1";

  serverAddress.sin_family = AF_INET;
  serverAddress.sin_port = htons(PORT);
  serverAddress.sin_addr.s_addr = inet_addr(ip.c_str());

  if (inet_pton(AF_INET, ip.c_str(), &serverAddress.sin_addr) < 0) {
    perror("INVALID IP");
    return false;
  }

  clear();
  move(0, 0);

  printw("REEGISTER OR LOGIN\n");
  printw("1 - REGISTER\n2 - LOGIN\n");

  refresh();

  int ch;
  ch = getch();

  ClientSession session;

  int client_fd = socket(AF_INET, SOCK_STREAM, 0);

  session.fd = client_fd;
  g_clients[client_fd] = session;

  uint8_t pkt_type;

  pkt_type = (ch == '1' || ch == 'r' || ch == 'R') ? 0x09 : 0x08;

  std::string name, pass;

  if (pkt_type == 0x09) {
    printw("------REGISTER------\n");
    refresh();
  } else {
    printw("------LOGIN------\n");
    refresh();
  }

  printw("USERNAME: ");
  refresh();
  name = read_input_line(62);

  printw("\nPASSWORD: ");
  refresh();
  pass = read_password(15);

  g_clients[client_fd].username = name;

  std::string creds = name + "|" + pass;

  if (connect(session.fd, (struct sockaddr *)&serverAddress,
              sizeof(serverAddress)) < 0) {
    perror("Error connecting to server");
    return false;
  }

  SSL *ssl = SSL_new(ssl_ctx);
  SSL_set_fd(ssl, client_fd);

  if (SSL_connect(ssl) <= 0) {
    std::cerr << "[TLS ERROR] Handshake failed on fd " << client_fd
              << std::endl;
    ERR_print_errors_fp(stderr);
    SSL_free(ssl);
    close(client_fd);
    return -1;
  }

  auto auth_packet = create_packet_stream(pkt_type, creds);
  SSL_write(ssl, auth_packet.data(), auth_packet.size());

  clear();
  move(0, 0);
  refresh();

  uint8_t response_buffer[256];
  ssize_t bytes_read = SSL_read(ssl, response_buffer, sizeof(response_buffer));

  if (bytes_read < static_cast<ssize_t>(sizeof(PacketHeader))) {
    cleanupNcurses();
    std::cerr << "Authentication failed: Server closed connection or sent no "
                 "response.\n";

    SSL_shutdown(ssl);
    close(client_fd);
    return -1;
  }

  PacketHeader auth_header;

  std::memcpy(&auth_header, response_buffer, sizeof(PacketHeader));
  uint32_t payload_length = ntohl(auth_header.payload_length);

  std::string ack_msg(reinterpret_cast<const char *>(response_buffer) +
                          sizeof(PacketHeader),
                      payload_length);

  if (ack_msg.find("OK") == std::string::npos ||
      ack_msg.find("NO") != std::string::npos) {
    cleanupNcurses();
    std::cerr << "Authentication / Registration failed: Server returned '"
              << ack_msg << "'\n";

    SSL_shutdown(ssl);
    close(client_fd);
    cleanupNcurses();
    return -1;
  }

  if (ack_msg.find("|") == std::string::npos) {
    close(client_fd);
    return -1;
  }

  std::string token = ack_msg.substr(ack_msg.find("|") + 1);

  g_clients[client_fd].ssl = ssl;
  g_clients[client_fd].token = token;

  clear();
  refresh();

  return client_fd;
}

SSL_CTX *init_client_ssl_context() {

  SSL_library_init();
  OpenSSL_add_all_algorithms();
  SSL_load_error_strings();

  const SSL_METHOD *method = TLS_client_method();
  SSL_CTX *ctx = SSL_CTX_new(method);

  if (!ctx) {
    ERR_print_errors_fp(stderr);
    exit(EXIT_FAILURE);
  }
  return ctx;
}

/**
 * @brief handles write event of the client
 *
 * @param input_buffer stores the outgoing data by the client
 * @param client_fd client file_descriptor
 * @return true : case client successfully writes to the buffer, false : case
 * faliure
 */
bool handle_write(std::string &input_buffer, int client_fd) {
  int ch;
  while ((ch = wgetch(inputWin)) != ERR) {
    if (ch == '\n' || ch == KEY_ENTER) {
      if (input_buffer == "/quit") {
        return false;
      }

      if (!input_buffer.empty()) {
        safePrint("[YOU] : " + input_buffer);

        input_buffer =
            "[" + g_clients[client_fd].username + "]: " + input_buffer;

        auto packet = create_packet_stream(0x01, input_buffer);

        SSL_write(g_clients[client_fd].ssl, packet.data(), packet.size());

        input_buffer.clear();
        werase(inputWin);
        wrefresh(inputWin);
      }
    } else if (ch == KEY_BACKSPACE || ch == 127) {
      if (!input_buffer.empty())
        input_buffer.pop_back();
    } else if (isprint(ch)) {
      input_buffer.push_back(static_cast<char>(ch));
    }

    werase(inputWin);
    mvwprintw(inputWin, 0, 0, "%s", input_buffer.c_str());
    wrefresh(inputWin);
  }

  return true;
}

/**
 * @brief handles the read event for client
 *
 * @param client_fd file descriptor of the client
 * @param rx_buffer stores data received from the server
 * @return false : case read fails, true : case read succeeded
 */
bool handle_read(int client_fd, std::vector<uint8_t> &rx_buffer) {
  uint8_t buffer[1024];
  ssize_t bytes_read =
      SSL_read(g_clients[client_fd].ssl, buffer, sizeof(buffer));

  if (bytes_read > 0) {
    g_last_server_activity = time(nullptr);
    rx_buffer.insert(rx_buffer.end(), buffer, buffer + bytes_read);

    while (rx_buffer.size() >= sizeof(PacketHeader)) {
      PacketHeader header;
      std::memcpy(&header, rx_buffer.data(), sizeof(PacketHeader));
      uint32_t payload_len = ntohl(header.payload_length);
      size_t total_size = payload_len + sizeof(PacketHeader);

      if (rx_buffer.size() < total_size) {
        break;
      }

      if (header.type == 0x06) {
        g_last_server_activity = time(nullptr);
        rx_buffer.erase(rx_buffer.begin(), rx_buffer.begin() + total_size);
        continue;
      }

      std::string msg(rx_buffer.begin() + sizeof(PacketHeader),
                      rx_buffer.begin() + total_size);

      safePrint(msg);

      rx_buffer.erase(rx_buffer.begin(), rx_buffer.begin() + total_size);
    }
  } else {
    int ssl_err = SSL_get_error(g_clients[client_fd].ssl, bytes_read);
    if (ssl_err == SSL_ERROR_WANT_READ || ssl_err == SSL_ERROR_WANT_WRITE) {
      return true;
    }
    safePrint("[SERVER] : CONNECTION LOST");
    return false;
  }

  return true;
}

bool check_client_timeout(int client_fd) {
  time_t now = time(nullptr);

  if (now - g_last_server_activity > 9) {
    safePrint("[SERVER] Connection lost (Heartbeat timeout). Exiting...", true);
    return false;
  }

  return true;
}

int attempt_reconnect(SSL_CTX *ssl_ctx, int old_fd,
                      const struct sockaddr_in &serverAddr) {
  safePrint("[SYSTEM] : Connection lost, Attemping reconnect....", true);

  std::string username = g_clients[old_fd].username;
  std::string token = g_clients[old_fd].token;

  if (g_clients.find(old_fd) != g_clients.end()) {
    if (g_clients[old_fd].ssl) {
      SSL_shutdown(g_clients[old_fd].ssl);
      SSL_free(g_clients[old_fd].ssl);
    }
    close(old_fd);
    g_clients.erase(old_fd);
  }

  int new_fd = -1;
  SSL *new_ssl = nullptr;
  bool reconnected = false;
  int num_reconnects = 0;

  while (!reconnected) {
    ++num_reconnects;

    if (num_reconnects > 6) {
      SSL_free(g_clients[old_fd].ssl);
      close(old_fd);
      g_clients.erase(old_fd);
      return -1;
    }

    new_fd = socket(AF_INET, SOCK_STREAM, 0);

    if (new_fd < 0) {
      sleep(1);
      continue;
    }

    if (connect(new_fd, (struct sockaddr *)&serverAddr, sizeof(serverAddr)) <
        0) {
      close(new_fd);
      sleep(2);
      continue;
    }

    new_ssl = SSL_new(ssl_ctx);
    SSL_set_fd(new_ssl, new_fd);

    if (SSL_connect(new_ssl) <= 0) {
      SSL_free(new_ssl);
      close(new_fd);
      sleep(2);
      continue;
    }

    std::string creds = username + "|" + token;
    auto auth_packet = create_packet_stream(0x0A, creds);

    if (SSL_write(new_ssl, auth_packet.data(), auth_packet.size()) <= 0) {
      SSL_free(new_ssl);
      close(new_fd);
      sleep(2);
      continue;
    }

    uint8_t response_buffer[256];
    int bytes_read =
        SSL_read(new_ssl, response_buffer, sizeof(response_buffer));

    if (bytes_read >= static_cast<int>(sizeof(PacketHeader))) {
      PacketHeader auth_header;
      std::memcpy(&auth_header, response_buffer, sizeof(PacketHeader));
      uint32_t payload_length = ntohl(auth_header.payload_length);

      std::string ack_msg(reinterpret_cast<const char *>(response_buffer) +
                              sizeof(PacketHeader),
                          payload_length);

      if (ack_msg == "OK") {
        reconnected = true;
      }
    }

    if (!reconnected) {
      SSL_free(new_ssl);
      close(new_fd);
      sleep(2);
    }
  }

  g_clients[new_fd] = ClientSession(new_fd, new_ssl);
  g_clients[new_fd].username = username;
  g_clients[new_fd].token = token;

  cleanupNcurses();
  setupNcurses();
  nodelay(inputWin, true);

  safePrint("[SYSTEM] Successfully reconnected to server!", true);
  return new_fd;
}

bool handle_connection_failure(SSL_CTX *ssl_ctx, int &client_fd, int kq) {
  int new_fd = attempt_reconnect(ssl_ctx, client_fd, serverAddress);

  if (new_fd < 0)
    return false;

  auto cleanup_new_connection = [&]() {
    auto it = g_clients.find(new_fd);

    if (it != g_clients.end()) {
      if (it->second.ssl) {
        SSL_free(it->second.ssl);
      }

      g_clients.erase(it);
    }

    close(new_fd);
  };

  if (!set_nonblocking(new_fd)) {
    perror("Failed to set new socket non-blocking");
    cleanup_new_connection();
    return false;
  }

  struct kevent ev;
  EV_SET(&ev, new_fd, EVFILT_READ, EV_ADD | EV_ENABLE, 0, 0, nullptr);

  if (kevent(kq, &ev, 1, nullptr, 0, nullptr) < 0) {
    perror("Failed to register new socket with kqueue");
    cleanup_new_connection();
    return false;
  }
  client_fd = new_fd;
  g_clients[client_fd].rx_buffer.clear();

  safePrint("[SYSTEM] Reconnected and registered successfully.", true);

  g_last_server_activity = time(nullptr);

  return true;
}

/**
 * @brief contains the main loop of the client, initializes the ncurses
 * screen, client connects, read & write handling
 * @return
 */
int main() {

  SSL_CTX *ssl_ctx = init_client_ssl_context();
  int client_fd = client_login(ssl_ctx);

  setupNcurses();
  g_last_server_activity = time(nullptr);
  nodelay(inputWin, true);

  if (client_fd < 0) {
    perror("LOGIN ERROR");
    return -1;
  }

  signal(SIGPIPE, SIG_IGN);

  set_nonblocking(client_fd);
  set_nonblocking(STDIN_FILENO);

  int kq = kqueue();

  struct kevent evs[3];

  EV_SET(&evs[0], client_fd, EVFILT_READ, EV_ADD | EV_ENABLE, 0, 0, nullptr);
  EV_SET(&evs[1], STDIN_FILENO, EVFILT_READ, EV_ADD | EV_ENABLE, 0, 0, nullptr);
  EV_SET(&evs[2], CLIENT_TIMER_IDENT, EVFILT_TIMER, EV_ADD | EV_ENABLE,
         NOTE_SECONDS, 5, nullptr);

  int kevent_error = 0;
  kevent_error = kevent(kq, evs, 3, nullptr, 0, nullptr);

  if (kevent_error < 0) {
    perror("kevent registration failed");
  }

  std::string input_buffer;
  std::vector<uint8_t> rx_buffer;
  std::vector<struct kevent> event_list(MAX_EVENTS);

  bool running = true;

  printf("IS IT FAILING HERE?");

  while (running) {
    int nevents =
        kevent(kq, nullptr, 0, event_list.data(), MAX_EVENTS, nullptr);
    if (nevents < 0) {
      if (errno == EINTR)
        continue;
      break;
    }

    for (int i = 0; i < nevents; ++i) {
      int current_fd = static_cast<int>(event_list[i].ident);

      if (event_list[i].filter == EVFILT_TIMER &&
          current_fd == CLIENT_TIMER_IDENT) {

        auto ping_pkt = create_packet_stream(PING, "");
        SSL_write(g_clients[client_fd].ssl, ping_pkt.data(), ping_pkt.size());

        if (!check_client_timeout(client_fd)) {
          running = handle_connection_failure(ssl_ctx, client_fd, kq);
        }
      }

      if (current_fd == STDIN_FILENO) {
        if (!handle_write(input_buffer, client_fd)) {
          running = false;
        }
      } else if (current_fd == client_fd &&
                 event_list[i].filter == EVFILT_READ) {
        if (!handle_read(client_fd, rx_buffer)) {
          running = handle_connection_failure(ssl_ctx, client_fd, kq);
        }
      }
    }
  }

  cleanupNcurses();
  close(kq);
  close(client_fd);
  return 0;
}
